################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.6
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gtp_exdes.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7a100t
## Package: fgg484
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 

################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################


create_clock -period 6.734 [get_ports Q0_CLK0_GTREFCLK_PAD_P_IN]





#create_clock -period 5.000 -name drpclk_in_i [get_ports DRP_CLK_IN_P]





# User Clock Constraints





set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/D}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *reset_on_error_in_r*/D}]
################################# RefClk Location constraints #####################
set_property PACKAGE_PIN F6 [get_ports Q0_CLK0_GTREFCLK_PAD_P_IN]
set_property PACKAGE_PIN E6 [get_ports Q0_CLK0_GTREFCLK_PAD_N_IN]

## LOC constrain for DRP_CLK_P/N
#set_property IOSTANDARD DIFF_SSTL15 [get_ports DRP_CLK_IN_P]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports DRP_CLK_IN_N]
#set_property PACKAGE_PIN R4 [get_ports DRP_CLK_IN_P]
#set_property PACKAGE_PIN T4 [get_ports DRP_CLK_IN_N]


set_property IOSTANDARD LVCMOS33 [get_ports {tx_disable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_disable[0]}]
set_property PACKAGE_PIN C22 [get_ports {tx_disable[0]}]
set_property PACKAGE_PIN C20 [get_ports {tx_disable[1]}]


################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells */gtp_exdes_m0/gtp_support_i/gtp_init_i/inst/gtp_i/gt0_gtp_i/gtpe2_i]
##---------- Set placement for gt1_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y5 [get_cells */gtp_exdes_m0/gtp_support_i/gtp_init_i/inst/gtp_i/gt1_gtp_i/gtpe2_i]
##---------- Set placement for gt2_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y6 [get_cells */gtp_exdes_m0/gtp_support_i/gtp_init_i/inst/gtp_i/gt2_gtp_i/gtpe2_i]
##---------- Set placement for gt3_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y7 [get_cells */gtp_exdes_m0/gtp_support_i/gtp_init_i/inst/gtp_i/gt3_gtp_i/gtpe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------

##############reset key define##################
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst]
set_property PACKAGE_PIN T6 [get_ports sys_rst]

############## key define##################
set_property PACKAGE_PIN B18 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]

set_property PACKAGE_PIN B17 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]

set_property PACKAGE_PIN A16 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]

set_property PACKAGE_PIN A15 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]

############## ºËÐÄ°åled define##################
set_property PACKAGE_PIN W5 [get_ports {led1}]
set_property IOSTANDARD SSTL15 [get_ports {led1}]

############## led define##################
set_property PACKAGE_PIN C17 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

set_property PACKAGE_PIN D17 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]

set_property PACKAGE_PIN V20 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]

set_property PACKAGE_PIN U20 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]

############## SD define##################
set_property IOSTANDARD LVCMOS33 [get_ports SD_clk]
set_property PACKAGE_PIN C14 [get_ports SD_clk]

set_property IOSTANDARD LVCMOS33 [get_ports SD_cs]
set_property PACKAGE_PIN A13 [get_ports SD_cs]

set_property IOSTANDARD LVCMOS33 [get_ports SD_datain]
set_property PACKAGE_PIN C15 [get_ports SD_datain]

set_property IOSTANDARD LVCMOS33 [get_ports SD_dataout]
set_property PACKAGE_PIN E17 [get_ports SD_dataout]

############## RS232 uart define##################
set_property IOSTANDARD LVCMOS33 [get_ports uart2_rx]
set_property PACKAGE_PIN AB10 [get_ports uart2_rx]

set_property IOSTANDARD LVCMOS33 [get_ports uart2_tx]
set_property PACKAGE_PIN AA9 [get_ports uart2_tx]

############## usb uart define##################
set_property IOSTANDARD LVCMOS33 [get_ports uart1_rx]
set_property PACKAGE_PIN Y12 [get_ports uart1_rx]

set_property IOSTANDARD LVCMOS33 [get_ports uart1_tx]
set_property PACKAGE_PIN Y11 [get_ports uart1_tx]

############## rtc define##################
set_property IOSTANDARD LVCMOS33 [get_ports DS1302_RST]
set_property PACKAGE_PIN D16 [get_ports DS1302_RST]

set_property IOSTANDARD LVCMOS33 [get_ports DS1302_SCLK]
set_property PACKAGE_PIN B15 [get_ports DS1302_SCLK]

set_property IOSTANDARD LVCMOS33 [get_ports DS1302_SIO]
set_property PACKAGE_PIN E16 [get_ports DS1302_SIO]

############## USB define##################
set_property IOSTANDARD LVCMOS33 [get_ports usb_slcs]
set_property PACKAGE_PIN P16 [get_ports usb_slcs]

set_property IOSTANDARD LVCMOS33 [get_ports usb_sloe]
set_property PACKAGE_PIN N13 [get_ports usb_sloe]

set_property IOSTANDARD LVCMOS33 [get_ports usb_slrd]
set_property PACKAGE_PIN P19 [get_ports usb_slrd]

set_property IOSTANDARD LVCMOS33 [get_ports usb_slwr]
set_property PACKAGE_PIN R19 [get_ports usb_slwr]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flaga]
set_property PACKAGE_PIN R18 [get_ports usb_flaga]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flagb]
set_property PACKAGE_PIN R14 [get_ports usb_flagb]

set_property IOSTANDARD LVCMOS33 [get_ports usb_flagc]
set_property PACKAGE_PIN P14 [get_ports usb_flagc]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[0]}]
set_property PACKAGE_PIN N14 [get_ports {usb_fifoaddr[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fifoaddr[1]}]
set_property PACKAGE_PIN N15 [get_ports {usb_fifoaddr[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[0]}]
set_property PACKAGE_PIN Y22 [get_ports {usb_fd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[1]}]
set_property PACKAGE_PIN W20 [get_ports {usb_fd[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[2]}]
set_property PACKAGE_PIN W19 [get_ports {usb_fd[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[3]}]
set_property PACKAGE_PIN Y19 [get_ports {usb_fd[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[4]}]
set_property PACKAGE_PIN Y18 [get_ports {usb_fd[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[5]}]
set_property PACKAGE_PIN V22 [get_ports {usb_fd[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[6]}]
set_property PACKAGE_PIN U22 [get_ports {usb_fd[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[7]}]
set_property PACKAGE_PIN T18 [get_ports {usb_fd[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[8]}]
set_property PACKAGE_PIN R17 [get_ports {usb_fd[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[9]}]
set_property PACKAGE_PIN R16 [get_ports {usb_fd[9]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[10]}]
set_property PACKAGE_PIN P15 [get_ports {usb_fd[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[11]}]
set_property PACKAGE_PIN N17 [get_ports {usb_fd[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[12]}]
set_property PACKAGE_PIN P17 [get_ports {usb_fd[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[13]}]
set_property PACKAGE_PIN U16 [get_ports {usb_fd[13]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[14]}]
set_property PACKAGE_PIN T16 [get_ports {usb_fd[14]}]

set_property IOSTANDARD LVCMOS33 [get_ports {usb_fd[15]}]
set_property PACKAGE_PIN U17 [get_ports {usb_fd[15]}]

############## ethernet RX define##################
create_clock -name rx_clk -period 8 [get_ports e_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports e_rxc]
set_property PACKAGE_PIN K18 [get_ports e_rxc]

set_property IOSTANDARD LVCMOS33 [get_ports e_rxdv]
set_property PACKAGE_PIN M22 [get_ports e_rxdv]

set_property IOSTANDARD LVCMOS33 [get_ports e_rxer]
set_property PACKAGE_PIN N19 [get_ports e_rxer]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[0]}]
set_property PACKAGE_PIN N22 [get_ports {e_rxd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[1]}]
set_property PACKAGE_PIN H18 [get_ports {e_rxd[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[2]}]
set_property PACKAGE_PIN H17 [get_ports {e_rxd[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[3]}]
set_property PACKAGE_PIN K19 [get_ports {e_rxd[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[4]}]
set_property PACKAGE_PIN M21 [get_ports {e_rxd[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[5]}]
set_property PACKAGE_PIN L21 [get_ports {e_rxd[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[6]}]
set_property PACKAGE_PIN N20 [get_ports {e_rxd[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[7]}]
set_property PACKAGE_PIN M20 [get_ports {e_rxd[7]}]

set_input_delay -clock rx_clk -max 3 [get_ports e_rxdv]
set_input_delay -clock rx_clk -min 2 [get_ports e_rxdv]

set_input_delay -clock rx_clk -max 3 [get_ports e_rxer]
set_input_delay -clock rx_clk -min 2 [get_ports e_rxer]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[0]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[0]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[1]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[1]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[2]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[2]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[3]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[3]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[4]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[4]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[5]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[5]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[6]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[6]}]

set_input_delay -clock rx_clk -max 3 [get_ports {e_rxd[7]}]
set_input_delay -clock rx_clk -min 2 [get_ports {e_rxd[7]}]

############## ethernet TX define##################
set_property IOSTANDARD LVCMOS33 [get_ports e_txc]
set_property PACKAGE_PIN J17 [get_ports e_txc]

set_property IOSTANDARD LVCMOS33 [get_ports e_gtxc]
set_property PACKAGE_PIN L18 [get_ports e_gtxc]

set_property IOSTANDARD LVCMOS33 [get_ports e_txen]
set_property PACKAGE_PIN M16 [get_ports e_txen]

set_property IOSTANDARD LVCMOS33 [get_ports e_txer]
set_property PACKAGE_PIN M13 [get_ports e_txer]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[0]}]
set_property PACKAGE_PIN M15 [get_ports {e_txd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[1]}]
set_property PACKAGE_PIN L14 [get_ports {e_txd[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[2]}]
set_property PACKAGE_PIN K16 [get_ports {e_txd[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[3]}]
set_property PACKAGE_PIN L16 [get_ports {e_txd[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[4]}]
set_property PACKAGE_PIN K17 [get_ports {e_txd[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[5]}]
set_property PACKAGE_PIN L20 [get_ports {e_txd[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[6]}]
set_property PACKAGE_PIN L19 [get_ports {e_txd[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[7]}]
set_property PACKAGE_PIN L13 [get_ports {e_txd[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports e_reset]
set_property PACKAGE_PIN L15 [get_ports e_reset]

create_clock -name tx_clk -period 8 [get_ports e_gtxc]

set_output_delay -clock tx_clk -max 3 [get_ports e_txen]
set_output_delay -clock tx_clk -min 0 [get_ports e_txen]

set_output_delay -clock tx_clk -max 3 [get_ports e_txer]
set_output_delay -clock tx_clk -min 0 [get_ports e_txer]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[0]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[0]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[1]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[1]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[2]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[2]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[3]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[3]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[4]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[4]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[5]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[5]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[6]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[6]}]

set_output_delay -clock tx_clk -max 3 [get_ports {e_txd[7]}]
set_output_delay -clock tx_clk -min 0 [get_ports {e_txd[7]}]

############## LCD define##################
set_property PACKAGE_PIN AB15 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN AA15 [get_ports {lcd_r[1]}]
set_property PACKAGE_PIN AA14 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN Y13 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN AB17 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN AB16 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN AA16 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN Y16 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN AB12 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN AB11 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN Y14 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN W14 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN C19 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN C18 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN F14 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN F13 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN E14 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN E13 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN D15 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN D14 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN B13 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN C13 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN AB13 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN AA13 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN A19 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN A18 [get_ports {lcd_hsync}]
set_property PACKAGE_PIN E18 [get_ports {lcd_vsync}]
set_property PACKAGE_PIN F18 [get_ports {lcd_de}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]

############## CMOS define##################
set_property PACKAGE_PIN F15 [get_ports {cmos1_sda}]
set_property PACKAGE_PIN H22 [get_ports {cmos1_scl}]
set_property PACKAGE_PIN K22 [get_ports {cmos1_d[7]}]
set_property PACKAGE_PIN K21 [get_ports {cmos1_d[6]}]
set_property PACKAGE_PIN J22 [get_ports {cmos1_d[3]}]
set_property PACKAGE_PIN G20 [get_ports {cmos1_d[1]}]
set_property PACKAGE_PIN H20 [get_ports {cmos1_d[2]}]
set_property PACKAGE_PIN G22 [get_ports {cmos1_d[4]}]
set_property PACKAGE_PIN D22 [get_ports {cmos1_d[5]}]
set_property PACKAGE_PIN D21 [get_ports {cmos1_d[0]}]
set_property PACKAGE_PIN E21 [get_ports {cmos1_pclk}]
set_property PACKAGE_PIN A21 [get_ports {cmos1_href}]
set_property PACKAGE_PIN B21 [get_ports {cmos1_vsync}]
set_property PACKAGE_PIN M17 [get_ports {cmos1_reset}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_reset}]

set_property PACKAGE_PIN J14 [get_ports {cmos2_scl}]
set_property PACKAGE_PIN K13 [get_ports {cmos2_sda}]
set_property PACKAGE_PIN K14 [get_ports {cmos2_d[7]}]
set_property PACKAGE_PIN H14 [get_ports {cmos2_d[4]}]
set_property PACKAGE_PIN H15 [get_ports {cmos2_d[5]}]
set_property PACKAGE_PIN J15 [get_ports {cmos2_d[0]}]
set_property PACKAGE_PIN H13 [get_ports {cmos2_d[6]}]
set_property PACKAGE_PIN J21 [get_ports {cmos2_d[1]}]
set_property PACKAGE_PIN G16 [get_ports {cmos2_d[2]}]
set_property PACKAGE_PIN G15 [get_ports {cmos2_d[3]}]
set_property PACKAGE_PIN G18 [get_ports {cmos2_vsync}]
set_property PACKAGE_PIN G17 [get_ports {cmos2_pclk}]
set_property PACKAGE_PIN G13 [get_ports {cmos2_href}]
set_property PACKAGE_PIN J20 [get_ports {cmos2_reset}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_pclk}]

############## VGA define##################
set_property IOSTANDARD LVCMOS33 [get_ports vga_clk]
set_property PACKAGE_PIN U21 [get_ports vga_clk]

set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property PACKAGE_PIN AA11 [get_ports vga_hs]

set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]
set_property PACKAGE_PIN AA10 [get_ports vga_vs]

set_property IOSTANDARD LVCMOS33 [get_ports vga_en]
set_property PACKAGE_PIN AB20 [get_ports vga_en]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN W12 [get_ports {vga_r[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN W11 [get_ports {vga_r[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN V14 [get_ports {vga_r[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN V13 [get_ports {vga_r[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[4]}]
set_property PACKAGE_PIN T15 [get_ports {vga_r[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[5]}]
set_property PACKAGE_PIN T14 [get_ports {vga_r[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[6]}]
set_property PACKAGE_PIN W16 [get_ports {vga_r[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[7]}]
set_property PACKAGE_PIN W15 [get_ports {vga_r[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN V17 [get_ports {vga_g[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN W17 [get_ports {vga_g[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN U15 [get_ports {vga_g[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN V15 [get_ports {vga_g[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[4]}]
set_property PACKAGE_PIN AB21 [get_ports {vga_g[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[5]}]
set_property PACKAGE_PIN AB22 [get_ports {vga_g[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[6]}]
set_property PACKAGE_PIN AA21 [get_ports {vga_g[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[7]}]
set_property PACKAGE_PIN AA20 [get_ports {vga_g[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN AA19 [get_ports {vga_b[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN AA18 [get_ports {vga_b[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN AB18 [get_ports {vga_b[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN T20 [get_ports {vga_b[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[4]}]
set_property PACKAGE_PIN Y17 [get_ports {vga_b[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[5]}]
set_property PACKAGE_PIN W22 [get_ports {vga_b[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[6]}]
set_property PACKAGE_PIN W21 [get_ports {vga_b[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[7]}]
set_property PACKAGE_PIN T21 [get_ports {vga_b[7]}]

          
##############DDR3 NET - IOSTANDARD ##################
# PadFunction: IO_L2P_T0_AD12P_35 
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[0]}]
set_property PACKAGE_PIN C2 [get_ports {ddr3_dq[0]}]

# PadFunction: IO_L5P_T0_AD13P_35 
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[1]}]
set_property PACKAGE_PIN G1 [get_ports {ddr3_dq[1]}]

# PadFunction: IO_L1N_T0_AD4N_35 
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[2]}]
set_property PACKAGE_PIN A1 [get_ports {ddr3_dq[2]}]

# PadFunction: IO_L6P_T0_35 
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[3]}]
set_property PACKAGE_PIN F3 [get_ports {ddr3_dq[3]}]

# PadFunction: IO_L2N_T0_AD12N_35 
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[4]}]
set_property PACKAGE_PIN B2 [get_ports {ddr3_dq[4]}]

# PadFunction: IO_L5N_T0_AD13N_35 
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[5]}]
set_property PACKAGE_PIN F1 [get_ports {ddr3_dq[5]}]

# PadFunction: IO_L1P_T0_AD4P_35 
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[6]}]
set_property PACKAGE_PIN B1 [get_ports {ddr3_dq[6]}]

# PadFunction: IO_L4P_T0_35 
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[7]}]
set_property PACKAGE_PIN E2 [get_ports {ddr3_dq[7]}]

# PadFunction: IO_L11P_T1_SRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[8]}]
set_property PACKAGE_PIN H3 [get_ports {ddr3_dq[8]}]

# PadFunction: IO_L11N_T1_SRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[9]}]
set_property PACKAGE_PIN G3 [get_ports {ddr3_dq[9]}]

# PadFunction: IO_L8P_T1_AD14P_35 
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[10]}]
set_property PACKAGE_PIN H2 [get_ports {ddr3_dq[10]}]

# PadFunction: IO_L10N_T1_AD15N_35 
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[11]}]
set_property PACKAGE_PIN H5 [get_ports {ddr3_dq[11]}]

# PadFunction: IO_L7N_T1_AD6N_35 
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[12]}]
set_property PACKAGE_PIN J1 [get_ports {ddr3_dq[12]}]

# PadFunction: IO_L10P_T1_AD15P_35 
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[13]}]
set_property PACKAGE_PIN J5 [get_ports {ddr3_dq[13]}]

# PadFunction: IO_L7P_T1_AD6P_35 
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[14]}]
set_property PACKAGE_PIN K1 [get_ports {ddr3_dq[14]}]

# PadFunction: IO_L12P_T1_MRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[15]}]
set_property PACKAGE_PIN H4 [get_ports {ddr3_dq[15]}]

# PadFunction: IO_L18N_T2_35 
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[16]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[16]}]
set_property PACKAGE_PIN L4 [get_ports {ddr3_dq[16]}]

# PadFunction: IO_L16P_T2_35 
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[17]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[17]}]
set_property PACKAGE_PIN M3 [get_ports {ddr3_dq[17]}]

# PadFunction: IO_L14P_T2_SRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[18]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[18]}]
set_property PACKAGE_PIN L3 [get_ports {ddr3_dq[18]}]

# PadFunction: IO_L17N_T2_35 
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[19]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[19]}]
set_property PACKAGE_PIN J6 [get_ports {ddr3_dq[19]}]

# PadFunction: IO_L14N_T2_SRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[20]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[20]}]
set_property PACKAGE_PIN K3 [get_ports {ddr3_dq[20]}]

# PadFunction: IO_L17P_T2_35 
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[21]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[21]}]
set_property PACKAGE_PIN K6 [get_ports {ddr3_dq[21]}]

# PadFunction: IO_L13N_T2_MRCC_35 
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[22]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[22]}]
set_property PACKAGE_PIN J4 [get_ports {ddr3_dq[22]}]

# PadFunction: IO_L18P_T2_35 
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[23]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[23]}]
set_property PACKAGE_PIN L5 [get_ports {ddr3_dq[23]}]

# PadFunction: IO_L20N_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[24]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[24]}]
set_property PACKAGE_PIN P1 [get_ports {ddr3_dq[24]}]

# PadFunction: IO_L19P_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[25]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[25]}]
set_property PACKAGE_PIN N4 [get_ports {ddr3_dq[25]}]

# PadFunction: IO_L20P_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[26]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[26]}]
set_property PACKAGE_PIN R1 [get_ports {ddr3_dq[26]}]

# PadFunction: IO_L22N_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[27]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[27]}]
set_property PACKAGE_PIN N2 [get_ports {ddr3_dq[27]}]

# PadFunction: IO_L23P_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[28]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[28]}]
set_property PACKAGE_PIN M6 [get_ports {ddr3_dq[28]}]

# PadFunction: IO_L24N_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[29]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[29]}]
set_property PACKAGE_PIN N5 [get_ports {ddr3_dq[29]}]

# PadFunction: IO_L24P_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[30]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[30]}]
set_property PACKAGE_PIN P6 [get_ports {ddr3_dq[30]}]

# PadFunction: IO_L22P_T3_35 
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dq[31]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[31]}]
set_property PACKAGE_PIN P2 [get_ports {ddr3_dq[31]}]

# PadFunction: IO_L6N_T0_VREF_34 
set_property SLEW FAST [get_ports {ddr3_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]
set_property PACKAGE_PIN V3 [get_ports {ddr3_addr[14]}]

# PadFunction: IO_L1N_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property PACKAGE_PIN U1 [get_ports {ddr3_addr[13]}]

# PadFunction: IO_L4N_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property PACKAGE_PIN Y2 [get_ports {ddr3_addr[12]}]

# PadFunction: IO_L4P_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property PACKAGE_PIN W2 [get_ports {ddr3_addr[11]}]

# PadFunction: IO_L5N_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property PACKAGE_PIN Y1 [get_ports {ddr3_addr[10]}]

# PadFunction: IO_L2P_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property PACKAGE_PIN U2 [get_ports {ddr3_addr[9]}]

# PadFunction: IO_L2N_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property PACKAGE_PIN V2 [get_ports {ddr3_addr[8]}]

# PadFunction: IO_L1P_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property PACKAGE_PIN T1 [get_ports {ddr3_addr[7]}]

# PadFunction: IO_L5P_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property PACKAGE_PIN W1 [get_ports {ddr3_addr[6]}]

# PadFunction: IO_L6P_T0_34 
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property PACKAGE_PIN U3 [get_ports {ddr3_addr[5]}]

# PadFunction: IO_L7N_T1_34 
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property PACKAGE_PIN AB1 [get_ports {ddr3_addr[4]}]

# PadFunction: IO_L10N_T1_34 
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property PACKAGE_PIN AB5 [get_ports {ddr3_addr[3]}]

# PadFunction: IO_L10P_T1_34 
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property PACKAGE_PIN AA5 [get_ports {ddr3_addr[2]}]

# PadFunction: IO_L8N_T1_34 
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property PACKAGE_PIN AB2 [get_ports {ddr3_addr[1]}]

# PadFunction: IO_L11N_T1_SRCC_34 
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property PACKAGE_PIN AA4 [get_ports {ddr3_addr[0]}]

# PadFunction: IO_L11P_T1_SRCC_34 
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property PACKAGE_PIN Y4 [get_ports {ddr3_ba[2]}]

# PadFunction: IO_L9P_T1_DQS_34 
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property PACKAGE_PIN Y3 [get_ports {ddr3_ba[1]}]

# PadFunction: IO_L9N_T1_DQS_34 
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property PACKAGE_PIN AA3 [get_ports {ddr3_ba[0]}]

# PadFunction: IO_L12P_T1_MRCC_34 
set_property SLEW FAST [get_ports {ddr3_ras_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ras_n}]
set_property PACKAGE_PIN V4 [get_ports {ddr3_ras_n}]

# PadFunction: IO_L12N_T1_MRCC_34 
set_property SLEW FAST [get_ports {ddr3_cas_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cas_n}]
set_property PACKAGE_PIN W4 [get_ports {ddr3_cas_n}]

# PadFunction: IO_L7P_T1_34 
set_property SLEW FAST [get_ports {ddr3_we_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_we_n}]
set_property PACKAGE_PIN AA1 [get_ports {ddr3_we_n}]

# PadFunction: IO_L15P_T2_DQS_34 
set_property SLEW FAST [get_ports {ddr3_reset_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {ddr3_reset_n}]
set_property PACKAGE_PIN W6 [get_ports {ddr3_reset_n}]

# PadFunction: IO_L14P_T2_SRCC_34 
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property PACKAGE_PIN T5 [get_ports {ddr3_cke[0]}]

# PadFunction: IO_L14N_T2_SRCC_34 
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property PACKAGE_PIN U5 [get_ports {ddr3_odt[0]}]

# PadFunction: IO_L8P_T1_34 
set_property SLEW FAST [get_ports {ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]
set_property PACKAGE_PIN AB3 [get_ports {ddr3_cs_n[0]}]

# PadFunction: IO_L4N_T0_35 
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property PACKAGE_PIN D2 [get_ports {ddr3_dm[0]}]

# PadFunction: IO_L8N_T1_AD14N_35 
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property PACKAGE_PIN G2 [get_ports {ddr3_dm[1]}]

# PadFunction: IO_L16N_T2_35 
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property PACKAGE_PIN M2 [get_ports {ddr3_dm[2]}]

# PadFunction: IO_L23N_T3_35 
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property PACKAGE_PIN M5 [get_ports {ddr3_dm[3]}]

# PadFunction: IO_L13P_T2_MRCC_34 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_p}]
set_property PACKAGE_PIN R4 [get_ports {sys_clk_p}]

# PadFunction: IO_L13N_T2_MRCC_34 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_n}]
set_property PACKAGE_PIN T4 [get_ports {sys_clk_n}]

# PadFunction: IO_L3P_T0_DQS_AD5P_35 
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[0]}]
set_property PACKAGE_PIN E1 [get_ports {ddr3_dqs_p[0]}]

# PadFunction: IO_L3N_T0_DQS_AD5N_35 
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[0]}]
set_property PACKAGE_PIN D1 [get_ports {ddr3_dqs_n[0]}]

# PadFunction: IO_L9P_T1_DQS_AD7P_35 
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[1]}]
set_property PACKAGE_PIN K2 [get_ports {ddr3_dqs_p[1]}]

# PadFunction: IO_L9N_T1_DQS_AD7N_35 
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[1]}]
set_property PACKAGE_PIN J2 [get_ports {ddr3_dqs_n[1]}]

# PadFunction: IO_L15P_T2_DQS_35 
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[2]}]
set_property PACKAGE_PIN M1 [get_ports {ddr3_dqs_p[2]}]

# PadFunction: IO_L15N_T2_DQS_35 
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[2]}]
set_property PACKAGE_PIN L1 [get_ports {ddr3_dqs_n[2]}]

# PadFunction: IO_L21P_T3_DQS_35 
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[3]}]
set_property PACKAGE_PIN P5 [get_ports {ddr3_dqs_p[3]}]

# PadFunction: IO_L21N_T3_DQS_35 
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[3]}]
set_property PACKAGE_PIN P4 [get_ports {ddr3_dqs_n[3]}]

# PadFunction: IO_L3P_T0_DQS_34 
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property PACKAGE_PIN R3 [get_ports {ddr3_ck_p[0]}]

# PadFunction: IO_L3N_T0_DQS_34 
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property PACKAGE_PIN R2 [get_ports {ddr3_ck_n[0]}]



set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]

## set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]



set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]

set_property LOC IN_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X1Y8 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]

set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]

set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]

set_property LOC OLOGIC_X1Y143 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y131 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y119 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X1Y107 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]

set_property LOC PLLE2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X1Y1 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]


set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -setup 6

set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -hold 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]
          
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
       
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
