set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
############## clock define##################
create_clock -period 5 [get_ports sys_clk_p]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]

##############reset key define##################
set_property PACKAGE_PIN T6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]

##############KEY1 define##################
set_property PACKAGE_PIN B18 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key1]

############## LCD define##################
set_property PACKAGE_PIN AB15 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN AA15 [get_ports {lcd_r[1]}]
set_property PACKAGE_PIN AA14 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN Y13 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN AB17 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN AB16 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN AA16 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN Y16 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN AB12 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN AB11 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN Y14 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN W14 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN C19 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN C18 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN F14 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN F13 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN E14 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN E13 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN D15 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN D14 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN B13 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN C13 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN AB13 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN AA13 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN A19 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN A18 [get_ports {lcd_hsync}]
set_property PACKAGE_PIN E18 [get_ports {lcd_vsync}]
set_property PACKAGE_PIN F18 [get_ports {lcd_de}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]



